apiVersion: v2
name: prometheus-stack
version: 0.1.0
dependencies:
  - name: kube-prometheus-stack
    version: 58.0.1  # Match latest available
    repository: https://prometheus-community.github.io/helm-charts
