# helm install prometheus prometheus-community/prometheus -f apps/monitoring/values.yaml


server:
  persistentVolume:
    enabled: true
    storageClass: "rook-ceph-block"  # Replace with your storage class, e.g., "my-storage-class"
    size: 8Gi  # Adjust size as needed

  ingress:
    enabled: true
    ingressClassName: traefik  # Specify Traefik as the ingress controller
    annotations:
      traefik.ingress.kubernetes.io/router.entrypoints: websecure  # Use websecure for HTTPS (adjust as needed)
      traefik.ingress.kubernetes.io/router.tls: "true"  # Enable TLS
    hosts:
      - "grafana.beg.xx.zombun.org"  # Replace with your hostname, e.g., prometheus.example.com
    paths:
      - /

alertmanager:
  persistentVolume:
    enabled: true
    storageClass: "rook-ceph-block"  # Replace with your storage class
    size: 2Gi  # Adjust size as needed

pushgateway:
  persistentVolume:
    enabled: true
    storageClass: "rook-ceph-block>"  # Replace with your storage class
    size: 2Gi  # Adjust size as needed