apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kubernetes-dashboard
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://kubernetes.github.io/dashboard/
    chart: kubernetes-dashboard
    targetRevision: 7.6.0  # Latest as of April 2025
    helm:
      valueFiles:
      - https://raw.githubusercontent.com/zombun/super-waffle/refs/heads/main/apps/kubernetes-dashboard/values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: kubernetes-dashboard
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kubernetes-dashboard-config
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/youruser/metallb-gitops.git
    targetRevision: HEAD
    path: manifests/kubernetes-dashboard
  destination:
    server: https://kubernetes.default.svc
    namespace: kubernetes-dashboard
  syncPolicy:
    automated:
      prune: true
      selfHeal: true