# apps/rook-ceph/rook-ceph-cluster-app.yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: rook-ceph-cluster
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  destination:
    namespace: rook-ceph
    server: https://kubernetes.default.svc
  project: default
  source:
    repoURL: https://github.com/zombun/super-waffle
    path: apps/rook-ceph
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
