apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: wordpress
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://charts.bitnami.com/bitnami
    chart: wordpress
    targetRevision: 24.1.18  # Bitnami WordPress chart version (as of latest stable)
    helm:
      values: |
        global:
          storageClass: rook-ceph-block
        wordpressUsername: admin
        wordpressPassword: supersecretpassword  # Change in production
        wordpressEmail: user@example.com
        wordpressFirstName: Admin
        wordpressLastName: User
        wordpressBlogName: My WordPress Blog
        mariadb:
          enabled: true
          primary:
            persistence:
              storageClass: rook-ceph-block
              size: 4Gi
        persistence:
          enabled: true
          storageClass: rook-ceph-block
          size: 10Gi
        service:
          type: ClusterIP
        ingress:
          enabled: true
          hostname: wordpress.local  # Replace with your domain
          annotations:
            kubernetes.io/ingress.class: nginx  # Adjust if using a different Ingress controller
        resources:
          requests:
            cpu: "300m"
            memory: "512Mi"
          limits:
            cpu: "500m"
            memory: "1024Mi"
  destination:
    server: https://kubernetes.default.svc
    namespace: wordpress
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true