# apps/rook-ceph/ceph-cluster.yaml
apiVersion: ceph.rook.io/v1
kind: CephCluster
metadata:
  name: rook-ceph
  namespace: rook-ceph
spec:
  cephVersion:
    image: quay.io/ceph/ceph:v18.2.4
    allowUnsupported: false
  dataDirHostPath: /var/lib/rook
  mon:
    count: 3
    allowMultiplePerNode: false
  mgr:
    count: 2
  dashboard:
    enabled: true
  network:
    hostNetwork: false
  storage:
    useAllNodes: true
    useAllDevices: false
    deviceFilter: "sdb"
    config:
      osdsPerDevice: "1"
  resources:
    api:
      requests:
          cpu: "125m"
          memory: "256Mi"
      limits:
        memory: "512Mi"
    mgr:
      requests:
          cpu: "125m"
          memory: "256Mi"
      limits:
        memory: "512Mi"
    mon:
      requests:
          cpu: "125m"
          memory: "256Mi"
      limits:
        memory: "512Mi"
    osd:
      requests:
          cpu: "125m"
          memory: "256Mi"
      limits:
        memory: "512Mi"