# values.yaml

# helm install mariadb bitnami/mariadb -f values.yaml --namespace mariadb


## mariadb-values.yaml
auth:
  rootPassword: "ls25"   
  database: "ls25"   
  username: "ls25"                
  password: "ls25"           

primary:
  persistence:
    enabled: true
    size: 8Gi
    storageClass: "rook-ceph-block" # Optional

resources:
  requests:
    memory: "512Mi"
    cpu: "250m"
  limits:
    memory: "1Gi"
    cpu: "500m"
