# values.yaml

# helm install mariadb bitnami/mariadb -f values.yaml --namespace mariadb

mariadb:
  rootPassword: "ls25"
  user: ls25"
  password: "ls25"
  database: "your-database"
  replicaCount: 1
  persistence:
    enabled: true
    size: 8Gi
    storageClass: "rook-ceph-block" # Set the correct storage class if needed
    accessMode: ReadWriteOnce
  primary:
    persistentVolume:
      storageClass: "rook-ceph-block" # Persistent volume for the primary instance
      size: 8Gi

service:
  type: ClusterIP
  port: 3306
