# apps/metallb/config.yaml
apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: traefik-pool
  namespace: metallb-system
  annotations:
    metallb.universe.tf/allow-shareid-ip: "true"
spec:
  addresses:
  - 10.255.0.29/32

---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: traefik-l2
  namespace: metallb-system
spec:
  ipAddressPools:
  - traefik-pool
