apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: nginx
  namespace: default
spec:
  entryPoints:
  - web
  routes:
  - match: Host(`nginx.10.255.0.29.nip.io`)
    kind: Rule
    services:
    - name: nginx
      port: 80