service:
  type: LoadBalancer
  annotations:
    service.beta.kubernetes.io/metal-lb: "true"
    metallb.universe.tf/address-pool: traefik-pool
    metallb.universe.tf/allow-shared-ip: "true"
  spec:
    loadBalancerIP: 10.255.0.29
ports:
  web:
    port: 8000
    exposedPort: 8000
    protocol: TCP
  websecure:
    port: 4430
    exposedPort: 4430
    protocol: TCP
deployment:
  enabled: true
  replicas: 1
securityContext:
  capabilities:
    drop: ["ALL"]
    add: ["NET_BIND_SERVICE"]  
  runAsUser: 0
  runAsGroup: 0
  runAsNonRoot: false
ingressRoute:
  dashboard:
    enabled: false
logs:
  general:
    level: DEBUG